export enum AppRoute {
  Main = "/",
  Basket = "/basket",
  Login = "/sign_in",
  Reg = "/sing_up",
  Trends = "/trends",
  Favorites = "/favorites",
  Settings = "/settings",
  Posts = "/posts",
  PostsAdd = "/posts/add",
  Register = "/sign_up",
  ForgotPassword = "/forgot_password",
  ResetPassword = "/reset_password",
  Activate = "/activate",
  NotFound = "404",
}
